[package]
name = "inobot"
version = "0.1.0"
authors = ["kuznetsovin <kuznetsovin@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.4"
curl = "0.4.8"
rusqlite = "0.12.0"